### PR TITLE
Default contact information in content and state should be linked by default

### PR DESCRIPTION
**Pull request by kennsippell**
This isn't a perfect fix including the interface changes described in #92, but I do think it is an improvement.

The "default contact" is the contact that is "getting forms filled about them" be default. Currently users set the default contact through the harness.defaults.json file - via its content.contact (and to some degree user.parent). This BRAC test is linking the two copies together, so when you edit one you edit the other. And the test is right to do so - they intuitively should be the same thing. But they are each a unique deep copy.

This change deep copies the default only once - then shares that instance in the multiple places it is used. Therefore, editing the data in one place results in it being updated in both.  

I think this is an easy step forward, but #92 should remain open. The interfaces for setting the contact information r pretty bad.

### CODE REVIEW

**Comment by kennsippell** [comment]
@freddieptf Would you check this out and give it a review?  You'd only need to review the *.js changes.  After this change, you shouldn't need [this confusing line](https://github.com/medic/config-brac/pull/213#discussion_r610708608) in your BRAC tests.

**Comment by freddieptf** [comment]
@kennsippell sorry, didn't see this. Sure let me check it out

**Review by derickl — APPROVED** [review]
Looks good for now

We should probably fail loudly if someone tries to mutate the harness properties. Otherwise, folks might think it a bug when the two diverge

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by freddieptf** [comment]
@kennsippell confirmed this fixed the issue in the BRAC test

**Comment by kennsippell** [comment]
@derickl Which objects are you suggesting to freeze?

**Comment by derickl** [comment]
I need to think through it a bit more

**Pull request merged**
