### PR TITLE
Rework jsdoc output for github pages

### LINKED ISSUE #91: Css on documentation page not loading due to CORS
Offical [README.md](https://github.com/medic/medic-conf-test-harness/blob/master/README.md) links to https://htmlpreview.github.io/?https://raw.githubusercontent.com/medic/medic-conf-test-harness/blob/master/out/index.html

This previously showed the full documentation + loaded all required CSS. Looks like the CSS is no longer loading and we need a better way to produce this documentation.

### PR DESCRIPTION
**Pull request by derickl**
Resolves #91 

After merging, we need to enable github-pages for the repository and point it to the docs directory

### CODE REVIEW

**Comment by kennsippell** [comment]
Turned on GitHub pages to test this. https://github.com/medic/medic-conf-test-harness/settings/pages. Should be accessible at http://docs.communityhealthtoolkit.org/medic-conf-test-harness/ but looks like an error. 

Can we also update README.md to point ot the new documentation destination?

**Review by kennsippell — APPROVED** [review]
This is great. Just the README link update and I think we're good to commit.

**Comment by derickl** [comment]
I think it's is by design that we are serving documentation from http://docs.communityhealthtoolkit.org/
Screenshot 2021-05-04 at 23 57 07

**Comment by derickl** [comment]
It seems new commits invalidates PR approvals. Back to you @kennsippell

**Pull request merged**
