### PR TITLE
getContactSummary expects a contact document, not a contact Id

### PR DESCRIPTION
**Pull request by kennsippell**
#71

### CODE REVIEW

**Comment by kennsippell** [comment]
@kitsao would you have a minute to review this harness update?

**Comment by kennsippell** [comment]
@derickl Can you help review this? Then I can merge and publish your change to chromium?

**Review by derickl — APPROVED** [review]
Looks good!

So has getContactSummary been essentially broken?

**Comment by kennsippell** [comment]
@derickl I guess there are three scenarios for this function:

`getContactSummary()` with no arguments. This was working
'getContactSummary(contactDoc, reports, lineage)` where you pass all the data. This was working fine.
`getContactSummary(contactDoc)` where you pass a contact only and the harness automatically loads the reports and lineage based on what it knows in the state. This was broken

**Pull request merged**
