### PR TITLE
verbose logging fix

### LINKED ISSUE #84: Verbose logging output from `.start()` even when { verbose: false } in options
Expected: When verbose: false, the harness should not have any logging events which are not errors or warnings
Observed: Every test class logs the following

```
Resolve chromium revision: 686378
Detecting local chromium ...
Detected chromium revision is already downloaded.
chromium executablePath: /home/kenn/.chromium-browser-snapshots/linux-686378/chrome-linux/chrome
chromium launchable: true
puppeteer version: 1.20.0
```

### PR DESCRIPTION
**Pull request by derickl**
Resolves #84

### CODE REVIEW

**Comment by derickl** [comment]
@kennsippell Curious if we should pass more options to the `PuppeteerChromiumResolver` constructor for more flexibility

**Review by kennsippell — APPROVED** [review]

**Comment by kennsippell** [comment]
@derickl What do you think? I think this is a good improvement, I'm not really clear on the utility of the other options.
For [launch](https://github.com/medic/medic-conf-test-harness/pull/90/files#diff-d356eda9f1d71e0f25fec3e869c8bcbfdbfd2cd258f70df3b3425188641ca33bR94) we just pass in the whole options object - but that starts to get sticky if you use it in too many places (eg. silent vs verbose).

I like what you have!

**Comment by kennsippell** [comment]
Actually, I saw "Error: Failed to launch chrome!" today in https://travis-ci.com/github/medic/config-muso/jobs/497920008. We might want to default `retry: 2` (probably new issue if you agree).

**Comment by derickl** [comment]
The default retry value is 3 - https://github.com/cenfun/puppeteer-chromium-resolver/blob/17c3359e2973f980e1f9724fe2d4840f37d16c66/index.js#L398

**Comment by derickl** [comment]
>What do you think? I think this is a good improvement, I'm not really clear on the utility of the other options.

I was of the same opinion since we only want to launch chrome with zero ceremony

**Pull request merged**
